version: "3"
services:
  hedgedoc:
    image: lscr.io/linuxserver/hedgedoc:latest
    container_name: hedgedoc
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=host
      - DB_PORT=3306
      - DB_USER=hedgedoc
      - DB_PASS=hedgepass
      - DB_NAME=hedgedoc
      - TZ=Europe/London
      - CMD_DOMAIN=hedgedoc.orians.org
      - CMD_URL_ADDPORT=false #optional
      - CMD_PROTOCOL_USESSL=false #optional
      - CMD_PORT=3000 #optional
#      - CMD_ALLOW_ORIGIN=['localhost'] #optional
    volumes:
      - /opt/DockerSwarmData/hedgedoc/config:/config
    ports:
      - 7700:3000
    restart: unless-stopped
    deploy:
            placement:
                constraints:
                    - node.hostname == client2

