version: "3"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/DockerSwarmData/heimdall/config:/config
    ports:
      - 6900:80
      - 6901:443
    restart: unless-stopped
    deploy:
            placement:
                constraints:
                    - node.hostname == client2

