version: "3"
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/DockerSwarmData/uptimekuma/config:/app/data
    ports:
      - 9300:3001
    restart: unless-stopped
    deploy:
            placement:
                constraints:
                    - node.hostname == client1
