# Run with
# ansible-playbook SetupPiwigo.yml
# http://piwigo.org/

---
- name: Setup Piwigo
  hosts: localhost
  connection: local
  tasks:

  - name: Create directory for data
    file:
      path: "{{ item }}"
      state: directory
      owner: ajorians
      group: users
      mode: 0777
    loop:
      - /mnt/DockerSwarmData/piwigo
      - /mnt/DockerSwarmData/piwigo/config
      - /mnt/DockerSwarmData/piwigo/gallery

  - name: Create Database
    community.mysql.mysql_db:
      name:
        - piwigo
      state: present

  - name: Grant user access
    community.mysql.mysql_user:
      state: present
      name: piwigo
      host: '%'
      password: dbpassword
      priv:
        'piwigo.*': 'ALL,GRANT'

  - name: Deploy Piwigo from a compose file
    docker_stack:
      state: present
      name: piwigo
      compose:
        - docker-compose.yml
