version: "3"
services:
  raneto:
    image: lscr.io/linuxserver/raneto:latest
    container_name: raneto
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/DockerSwarmData/raneto/config:/config
    ports:
      - 8700:3000
    restart: unless-stopped
    deploy:
            placement:
                constraints:
                    - node.hostname == client2
