version: "3"
services:
  pidgin:
    image: lscr.io/linuxserver/pidgin:latest
    container_name: pidgin
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/DockerSwarmData/pidgin/config:/config
    ports:
      - 7100:3000
    restart: unless-stopped
    deploy:
            placement:
                constraints:
                    - node.hostname == client1

