version: "3"
services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/DockerSwarmData/grocy/config:/config
    ports:
      - 8500:80
    restart: unless-stopped
    deploy:
            placement:
                constraints:
                    - node.hostname == client2
