version: "3"
services:
  thelounge:
    image: lscr.io/linuxserver/thelounge:latest
    container_name: thelounge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/DockerSwarmData/thelounge/config:/config
    ports:
      - 7400:9000
    restart: unless-stopped
    deploy:
            placement:
                constraints:
                    - node.hostname == client2

