version: "3"
services:
  lychee:
    image: lscr.io/linuxserver/lychee:latest
    container_name: lychee
    restart: always
    volumes:
      - /opt/DockerSwarmData/lychee/config:/config
      - /opt/DockerSwarmData/lychee/pictures:/pictures
    environment:
      - DB_HOST=host
      - DB_USERNAME=lychee
      - DB_PASSWORD=dbpassword
      - DB_DATABASE=lychee
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=America/Detroit
    ports:
      - 5300:80
    deploy:
            placement:
                constraints:
                    - node.hostname == client1
