version: "3"
services:
  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - PMA_ARBITRARY=1 #optional
      - PMA_ABSOLUTE_URI=https://phpmyadmin.orians.org
    volumes:
      - /opt/DockerSwarmData/phpmyadmin/config:/config
    ports:
      - 6700:80
    restart: unless-stopped
    deploy:
            placement:
                constraints:
                    - node.hostname == client1

