# Run with
# ansible-playbook SetupBabybuddy.yml
# https://github.com/babybuddy/babybuddy

---
- name: Setup Babybuddy
  hosts: localhost
  connection: local
  tasks:

  - name: Create directory for data
    file:
      path: "{{ item }}"
      state: directory
      owner: ajorians
      group: users
      mode: 0777
    loop:
      - /mnt/DockerSwarmData/babybuddy
      - /mnt/DockerSwarmData/babybuddy/config

  - name: Deploy Babybuddy from a compose file
    docker_stack:
      state: present
      name: babybuddy
      compose:
        - docker-compose.yml
