version: "3"
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - /opt/DockerSwarmData/calibre/config:/config
    ports:
      - 6401:8080
      - 6402:8081
    restart: unless-stopped
    deploy:
            placement:
                constraints:
                    - node.hostname == client2
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /opt/DockerSwarmData/calibre/config:/config
      - /opt/DockerSwarmData/calibre/library:/books
    ports:
      - 6400:8083
    deploy:
            placement:
                constraints:
                    - node.hostname == client2
