# Run with
# ansible-playbook SetupGrav.yml

---
- name: Setup Grav
  hosts: localhost
  connection: local
  tasks:

  - name: Create directory for data
    file:
      path: "{{ item }}"
      state: directory
      owner: ajorians
      group: users
      mode: 1777
    loop:
      - /mnt/DockerSwarmData/grav
      - /mnt/DockerSwarmData/grav/config

  - name: Deploy grav from a compose file
    docker_stack:
      state: present
      name: grav
      compose:
        - docker-compose.yml
