version: "3"
services:
  ubooquity:
    image: lscr.io/linuxserver/ubooquity:latest
    container_name: ubooquity
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - MAXMEM=512
    volumes:
      - /opt/DockerSwarmData/ubooquity/config:/config
      - /opt/DockerSwarmData/ubooquity/books:/books
      - /opt/DockerSwarmData/ubooquity/comics:/comics
      - /opt/DockerSwarmData/ubooquity/files:/files
    ports:
      - 6500:2202
      - 6501:2203
    restart: unless-stopped
    deploy:
            placement:
                constraints:
                    - node.hostname == client1

