# Run with
# ansible-playbook SetupMonica.yml
# https://www.monicahq.com/

---
- name: Setup Monica
  hosts: localhost
  connection: local
  tasks:

  - name: Create directory for data
    file:
      path: "{{ item }}"
      state: directory
      owner: ajorians
      group: users
      mode: 0777
    loop:
      - /mnt/DockerSwarmData/monica
      - /mnt/DockerSwarmData/monica/storage

  - name: Create Database
    community.mysql.mysql_db:
      login_user: root
      name:
        - monica
      state: present

  - name: Grant user access
    community.mysql.mysql_user:
      login_user: root
      state: present
      name: monicauser
      host: '%'
      password: dbpassword 
      priv:
        'monica.*': 'ALL,GRANT'

  - name: Deploy Monica from a compose file
    docker_stack:
      state: present
      name: monica
      compose:
        - docker-compose.yml
