version: "3"
services:
  snapdrop:
    image: lscr.io/linuxserver/snapdrop:latest
    container_name: snapdrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/DockerSwarmData/snapdrop/config:/config
    ports:
      - 7200:80
      - 7201:443
    restart: unless-stopped
    deploy:
            placement:
                constraints:
                    - node.hostname == client2

